hyperskill_project:
  id: 181
  ide_files: https://stepik.org/media/attachments/lesson/529078/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Sat, 02 Oct 2021 06:01:10 UTC
stages:
- id: 913
  step: 13093
  is_completed: true
- id: 914
  step: 13094
  is_completed: true
- id: 915
  step: 13095
  is_completed: true
- id: 916
  step: 13096
  is_completed: true
topics:
  0:
  - title: Binary numbers
    theory_id: 5544
  - title: Converting from decimal to binary
    theory_id: 5614
  - title: Hexadecimal numbers
    theory_id: 8788
  - title: Octal numbers
    theory_id: 11949
  - title: Units of information
    theory_id: 6865
  - title: Introduction to Java
    theory_id: 3500
  - title: Basic literals
    theory_id: 3522
  - title: Overview of the basic program
    theory_id: 3521
  - title: Printing data
    theory_id: 3749
  - title: Types and variables
    theory_id: 3518
  - title: Sizes and ranges
    theory_id: 3532
  - title: Comments
    theory_id: 3520
  - title: Coding style conventions
    theory_id: 12411
  - title: Naming variables
    theory_id: 3513
  - title: Scanning the input
    theory_id: 9055
  - title: Arithmetic operations
    theory_id: 3519
  - title: Integer types and operations
    theory_id: 3565
  - title: Boolean and logical operations
    theory_id: 3516
  - title: Relational operators
    theory_id: 3512
  - title: Increment and decrement
    theory_id: 5008
  - title: Floating-point types
    theory_id: 3517
  - title: Conditional statement
    theory_id: 3503
  - title: Ternary operator
    theory_id: 3506
  - title: The while and do-while loops
    theory_id: 3498
  1:
  - title: Converting from binary to decimal
    theory_id: 5622
  - title: Write, compile, and run
    theory_id: 3739
  - title: Computer programming
    theory_id: 8739
  - title: Type casting
    theory_id: 3510
  - title: Introduction to OOP
    theory_id: 3614
  - title: Characters
    theory_id: 3514
  - title: The for-loop
    theory_id: 3505
  - title: Branching statements
    theory_id: 3507
  - title: Switch statement
    theory_id: 3504
  - title: Calling a method
    theory_id: 10973
  - title: Declaring a method
    theory_id: 10982
  - title: The main method
    theory_id: 3489
  - title: Functional decomposition
    theory_id: 10570
  - title: Primitive and reference types
    theory_id: 5035
  - title: Array
    theory_id: 3511
  - title: String
    theory_id: 3523
  - title: Processing strings
    theory_id: 3551
  - title: Numeric literals
    theory_id: 10545
  - title: Math library
    theory_id: 3501
  - title: Defining classes
    theory_id: 3618
  - title: Objects
    theory_id: 4727
  - title: Interface
    theory_id: 3615
  - title: Comparable
    theory_id: 14456
  2:
  - title: BigInteger
    theory_id: 3508
  3:
  - title: 'Decimal to binary: fractions'
    theory_id: 11938
  - title: BigDecimal
    theory_id: 13511
